# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          IP: ${{ secrets.REGRUIP }}
          REGPWD: ${{ secrets.REGRUP }}
          TG_NOTIFICATIONS: ${{ vars.TG_NOTIFICATIONS_BOT_TOKEN  }}
          TG_OFFERS: ${{ vars.TG_OFFER_CHATS_BOT_TOKEN }}
        run: cat $REGPWD | ssh -o "StrictHostKeyChecking=no" -o "PasswordAuthentication=yes" -v root@$IP "export TG_NOTIFICATIONS_BOT_TOKEN=$TG_NOTIFICATIONS && export TG_OFFER_CHATS_BOT_TOKEN=$TG_OFFERS && ./deploy.sh"
