# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

          # printf $REGPWD | ssh -o 'StrictHostKeyChecking=no' -tt root@$IP "export TG_NOTIFICATIONS_BOT_TOKEN=$TG_NOTIFICATIONS && export TG_OFFER_CHATS_BOT_TOKEN=$TG_OFFERS && ./deploy.sh"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install expect
        run: sudo apt-get install expect 
      - shell: bash
        env:
          IP: ${{ secrets.REGRUIP }}
          REGPWD: ${{ secrets.REGRUP }}
          TG_NOTIFICATIONS: ${{ vars.TG_NOTIFICATIONS_BOT_TOKEN  }}
          TG_OFFERS: ${{ vars.TG_OFFER_CHATS_BOT_TOKEN }}
        run: |
          expect -c 'spawn ssh root@$env(IP) "export TG_NOTIFICATIONS_BOT_TOKEN=$env(TG_NOTIFICATIONS) && export TG_OFFER_CHATS_BOT_TOKEN=$env(TG_OFFERS) && ./deploy.sh"; expect "re you sure you want to continue connecting"; send "yes\r"; interact; expect "password: "; send "$env(REGPWD)\r"; interact'
