# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          host='${{ secrets.REGRUIP }}'
          hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
          ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts
      - name: Connect to server
        shell: bash
        env:
          IP: ${{ secrets.REGRUIP }}
          REGPWD: ${{ secrets.REGRUP }}
          TG_NOTIFICATIONS: ${{ vars.TG_NOTIFICATIONS_BOT_TOKEN }}
          TG_OFFERS: ${{ vars.TG_OFFER_CHATS_BOT_TOKEN }}
        run: |
          ssh -o "StrictHostKeyChecking=no" root@${{env.IP}} "export PROD=true && export TG_NOTIFICATIONS_BOT_TOKEN=${{env.TG_NOTIFICATIONS}} && export TG_OFFER_CHATS_BOT_TOKEN=${{env.TG_OFFERS}} && cd ~/src && rm -rf ./fl-bot && git clone git@github.com:DRublev/fl-bot.git && cd ./fl-bot && /usr/local/go/bin/go build -v && pm2 del fl-bot && TG_OFFER_CHATS_BOT_TOKEN=${{env.TG_OFFERS}} TG_NOTIFICATIONS_BOT_TOKEN=${{env.TG_NOTIFICATIONS}} pm2 start ./main --name fl-bot -l ~/logs/log_${{github.sha}} && echo 1"
